name: Cypress Test

on: [push]

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with:
          start: npm run runOnChrome
    artificats:
      - path: .
      - when: always
